services:

  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: appstore
      POSTGRES_DB: appstore

  registry:
    image: registry:latest
    volumes:
      - registry_data:/data
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data

  backend:
    build:
      context: backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
      - registry
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      target: dev-server
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  registry_data:
