spring:
  application:
    name: appstore
  datasource:
    password: ${DB_PASSWORD:password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appstore}
    username: ${DB_USERNAME:appstore}
  hibernate:
    ddl-auto: drop-create
    show-sql: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    generate-ddl: true
  liquibase:
    enabled: true
    change-log: classpath:master-changelog.yml
  security:
    basic:
      enabled: false
    ignored: ${API_PREFIX:/api/}\*\*
  management:
    security:
      enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  registry:
    impl: ${REGISTRY_IMPL:docker} # possible values [docker.default]
    scheme: ${REGISTRY_HTTP_SCHEME:http}
    host: ${REGISTRY_URL:registry}:${REGISTRY_PORT:5000}
    url: ${registry.scheme:http}://${registry.host}
