name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: cytomine/postgis:${{ vars.POSTGIS_VERSION }}
        env:
          POSTGRES_NAME: appstore
          POSTGRES_USER: appstore
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ vars.JAVA_DIST }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ vars.GRADLE_VERSION }}

      - name: Test backend
        run: gradle :test --no-daemon
        env:
          DB_NAME: appstore
          DB_USERNAME: appstore
          DB_PASSWORD: password

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: backend/build/reports/
          retention-days: 7

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/build/test-results/
          retention-days: 7

      - name: Upload Java Code Coverage (JaCoCo)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: jacoco
          path: backend/build/jacoco/
          retention-days: 7
